### ISSUE TITLE
printf escaping issue in @go.log

### ISSUE THREAD

**Issue by JohnOmernik** [mbland/go-script-bash#55] opened 2016-12-23 20:26 UTC
I am trying to log a json output from an API with @go.log 

The value of the variable I am printing is

{"timestamp":1482524700778,"timeofday":"2016-12-23 08:25:00.778 GMT+0000","status":"OK","total":0,"data":[],"messages":["Successfully created volume: 'zeta.shared.dockerregv2'"]}

The error I am getting is:

/home/zetaadm/zetago/scripts/go-script-bash/lib/log: line 172: printf: `m': invalid format character

**Comment by mbland** [comment] 2016-12-23 20:35
This is a dupe of #47. Also, never fear; I've got a fix finished and tested (with a batch of other small issues and improvements), and will push it a little later today. :-)

**Comment by mbland** [comment] 2016-12-23 20:36
Actually, crap, wait... I was confusing the `invalid format character` with the `%` escaping issue. I need to add `"` escaping to the fix, too. Sorry about the early close!

**Comment by mbland** [comment] 2016-12-23 22:32
Hey @JohnOmernik, can you post the version tag or commit has you're sync'd to, and the line that you're using to call `@go.log` in this case?

**Comment by mbland** [comment] 2016-12-23 23:10
I've written test cases with both a `"Hello, World!"` string as well as the exact string you posted above, and can get neither to fail either on the current tip of master (commit b04e952b5ea57e247f0f371e54cf81d639db74a4) or on `v1.2.0`. Tried scouring your most recently pushed branch (`installzeta` at commit 620d3d681932c28ca0da388793b9c845cf0bd9cb), which is currently locked to v1.2.0, but haven't yet found a call that seems to be the one in question.

I thought maybe it might be from `maprapi` in `scripts/lib/libmapr`, but even adding `Result: ` to the log message didn't seem to tickle the same condition.

Here's the tests I've written, in a branch I haven't pushed yet, but that is based on the current master. In my branch, all three pass; on master and v1.2.0, only the first fails:

```bash
@test "$SUITE: log INFO handle '%' in message arguments" {
  run_log_script '@go.log INFO Timestamp is "%Y-%m-%d %H:%M:%S"'
  assert_success
  assert_log_equals INFO 'Timestamp is %Y-%m-%d %H:%M:%S'
}

@test "$SUITE: log INFO handle '\"' in message arguments" {
  run_log_script '@go.log INFO "\"Hello, World!\""'
  assert_success
  assert_log_equals INFO '"Hello, World!"'
}

@test "$SUITE: log INFO handle '\"' in message arguments (issue 55)" {
  local json_log_msg=(
    '{"timestamp":1482524700778,'
    '"timeofday":"2016-12-23 08:25:00.778 GMT+0000",'
    '"status":"OK","total":0,"data":[],'
    "\"messages\":[\"Successfully created volume: 'zeta.shared.dockerregv2'\"]}"
  )
  json_log_msg="${json_log_msg[*]}"
  json_log_msg="${json_log_msg//, "/,"}"
  JSON_LOG_MSG="$json_log_msg" run_log_script \
    "@go.log INFO \"Result: \$JSON_LOG_MSG\""
  assert_success
  assert_log_equals INFO "Result: $json_log_msg"
}
```

As soon as you can post the exact call in the code (better if it's in a commit!), I'll see if there's anything missing that I can try to reproduce. But the `invalid format character` smells a lot more like an unescaped `%` than a quoting issue at the moment, despite the fact that `%` doesn't appear in your example string.

Also, I'll push and merge my new branch a little later. If you could update your submodule to match master after I've done that and try your script again, I'd be curious if the problem goes away because it was actually a `%` somewhere.

**Comment by JohnOmernik** [comment] 2016-12-23 23:12
Sure its v1.2.0 I am pretty sure, and the line I am using this:

CMD="/volume/create?name=zeta.shared.dockerregv2&path=/zeta/shared/dockerregv2/images&rootdirperms=775&user=zetaadm:fc,a,dump,restore,m,d%20mapr:fc,a,dump,restore,m,d&ae=zetaadm"

@go.log INFO "Command: $CMD"

So it may be the the %?

**Comment by mbland** [comment] 2016-12-23 23:46
Almost certainly it is. I'll ping you when I push tonight, but in the interim, you can cheat by writing this:

```bash
@go.log INFO "Command: ${CMD//%/%%}"
```

This _will_ break after I push my update, so if you do it, make sure to put a big TODO to remove it later.

**Comment by mbland** [comment] 2016-12-24 03:08
OK, so #56 is about to land in master momentarily, and when it does it will automatically close this issue and #47. It doesn't have all the stuff I planned to get in today, but I wanted to make sure you had access to the fixed `log` module.

**Closed as completed** 2016-12-24 03:11 UTC
Labels: bug
